version: "3"
services:
  cassandra-0:
    image: cassandra:latest
#    restart: always
#    networks:
#      broker:
#        ipv4_address: 172.18.0.10
    ports:
#      - 7000:7000
      - 9042:9042
    volumes:
#      - /home/cassandra-node-0/commitlog:/var/lib/cassandra/commitlog
#      - /home/cassandra-node-0/hints:/var/lib/cassandra/hints
#      - /home/cassandra-node-0/data:/var/lib/cassandra/data
#      - /home/cassandra-node-0/saved_caches:/var/lib/cassandra/saved_caches
#      - /home/cassandra-node-0/logs:/var/log/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
#      - ./init-keyspace.cql:/docker-entrypoint-initdb.d/init-keyspace.cql
    environment:
      - CASSANDRA_SEEDS=cassandra-0
      - CASSANDRA_CLUSTER_NAME=cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=8G
      - HEAP_NEWSIZE=200M


  loki:
    image: grafana/loki:latest
    depends_on:
      - cassandra-0
    restart: always
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - 4000:4000

  hello-world:
    image: hello_world:latest
    ports:
      - 8011:8011
    logging:
        driver: loki
        options:
          loki-url: http://localhost:4000/loki/api/v1/push
          loki-pipeline-stages: |
            - regex:
                expression: '(level|lvl|severity)=(?P<level>\w+)'
            - drop:
                expression: 'filename'
            - labels:
                level:
          loki-relabel-config: |
            - regex: filename|source
              action: labeldrop
