auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 1073741824

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 2m       # Any chunk not receiving new logs in this time will be flushed
  chunk_target_size: 1048576  #1073741824
  max_chunk_age: 5m           # All chunks will be flushed when they hit this age, default is 1h
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
    resync_interval: 5s
#  aws:
#    s3: http://minioadmin:minioadmin@minio.:9000/loki
#    s3forcepathstyle: true
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
#  retention_enabled: true
#  retention_delete_delay: 0s

limits_config:
#  retention_period: 5m
#  reject_old_samples: true
#  reject_old_samples_max_age: 15m
  max_global_streams_per_user: 5000
  max_query_length: 0h # Default: 721h
  max_query_parallelism: 32 # Old Default: 14
  max_streams_per_user: 0 # Old Default: 10000
#  ingestion_rate_mb: 8
#  ingestion_burst_size_mb: 16



chunk_store_config:
  max_look_back_period: 0s

#table_manager:
#  retention_deletes_enabled: true
#  retention_period: 3m

query_range:
  split_queries_by_interval: 0
  parallelise_shardable_queries: false

querier:
  max_concurrent: 2048

frontend:
  max_outstanding_per_tenant: 5096
  compress_responses: true


#ruler:
#  storage:
#    type: local
#    local:
#      directory: /loki/rules
#  rule_path: /loki/rules-temp
#  alertmanager_url: http://localhost:9093
#  ring:
#    kvstore:
#      store: inmemory
#  enable_api: true
